### PR TITLE
Keep suggesting index on incoming message

### LINKED ISSUE #254: Suggestions resets to the first position when a message is received
# Summary

When browsing suggested profiles, receiving a message resets the "carousel" to the initial position.

# Steps to reproduce

 1. Have someone send you messages
 2. Go to chat suggestions
 3. Browse beyond the first one

### PR DESCRIPTION
**Pull request by easafe**
Fixes #254

### CODE REVIEW

**Comment by Iizuki** [comment]
So it removes the sender from suggestions when a new message arrives (makes sense), but this also updated the currently shown suggestion regardless of whether it was a from someone in the previous suggestions?

**Comment by easafe** [comment]
The fix is that if whoever sent the message is not removed from the suggestions then keep it as it is

**Comment by easafe** [comment]
(it being the suggestion index)

**Comment by Iizuki** [comment]
Seems good.

In the less likely event that it was someone from the suggestions, but not the one you're currently staring, it will still jump? (or even in the case that it was the person you're staring, but then it makes sense anyway)

**Comment by easafe** [comment]
it should move only if the index matches

**Pull request merged**
